### ISSUE TITLE
Custom types commit title seems to fail

### ISSUE THREAD

**Issue by Clumsy-Coder** [zeke/semantic-pull-requests#110] opened 2020-08-11 21:39 UTC
Using custom types seems to fail semantic-pull-requests checks

ex: commit title 

refactoring(semantic-release): ♻️  comment out property 'emoji' and 'code'

---

`.github/semantic.yml`

```yml
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - style
  - perf
  - prune
  - fix
  - quickfix
  - feature
  - docs
  - deploy
  - ui
  - init
  - test
  - security
  - osx
  - linux
  - windows
  - android
  - ios
  - release
  - lint
  - wip
  - fix-ci
  - downgrade
  - upgrade
  - pushpin
  - ci
  - analytics
  - refactoring
  - docker
  - dep-add
  - dep-rm
  - config
  - i18n
  - typo
  - poo
  - revert
  - merge
  - dep-up
  - compat
  - mv
  - license
  - breaking
  - assets
  - review
  - access
  - docs-code
  - beer
  - texts
  - db
  - log-add
  - log-rm
  - contrib-add
  - ux
  - arch
  - iphone
  - clown-face
  - egg
  - see-no-evil
  - camera-flash
  - experiment
  - seo
  - k8s
  - types
  - seed
  - flags
  - animation

```

**Comment by zeke** [comment] 2020-08-25 04:23
I think you may also need to specify valid `scopes` in your config:

```yml
scopes:
  - semantic-release
  ...
```

Please let me know if that works.

**Comment by Clumsy-Coder** [comment] 2020-08-30 00:49
Is there a way to use it without defining scopes? 

Or is there a way to accept any scope?

**Comment by zeke** [comment] 2020-09-09 03:25
> Is there a way to use it without defining scopes?

Using a commit without a scope e.g. `refactoring: comment out property` should work, or you can define the allowed scopes in your config. I'm going close this issue since this is expected behavior and not actually a bug.

> Or is there a way to accept any scope?

No, but if you want that functionality I'd consider accepting a pull request that adds support for it. 👍🏼

**Closed by zeke** 2020-09-09 03:25 UTC
